# apiVersion: networking.istio.io/v1alpha3
# kind: EnvoyFilter
# metadata:
#   name: search-inbound-filter
#   namespace: hr2
# spec:
#   workloadSelector:
#     labels:
#       io.kompose.service: search  # 匹配search服务的Pod标签
#   configPatches:
#   - applyTo: HTTP_FILTER
#     match:
#       context: SIDECAR_INBOUND
#       listener:
#         portNumber: 8082
#         filterChain:
#           filter:
#             name: "envoy.filters.network.http_connection_manager"
#             subFilter:
#               name: "envoy.filters.http.router"
#     patch:
#       operation: INSERT_BEFORE
#       value:
#         name: envoy.filters.http.lua
#         typed_config:
#           "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
#           defaultSourceCode:
#             inlineString: |
#               function envoy_on_request(request_handle)
#                 -- 打印请求头
#                 request_handle:logInfo("=== Request Headers ===")
#                 for name, value in pairs(headers) do
#                   request_handle:logInfo(string.format("%s: %s", name, value))
#                 end

#                 local auth = request_handle:headers():get("x-custom-auth")
                
#                 if auth ~= "verified" then
#                   request_handle:logErr(string.format("[gRPC AUTH] Invalid auth header: %s", tostring(auth)))
#                   request_handle:respond(
#                     {
#                       [":status"] = "500",
#                       ["content-type"] = "application/grpc",
#                       ["grpc-status"] = "16",
#                       ["grpc-message"] = "Missing valid authentication header"
#                     },
#                     ""  -- 空响应体
#                   )
#                 end
#               end