apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
        proxy.istio.io/config: |
          proxyStatsMatcher:
            inclusionPrefixes:
            - "cluster.outbound"
            - "http"
            inclusionRegexps:
            - ".*grpc.*"  # 增加gRPC相关统计
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - command:
            - frontend
          image: deathstarbench/hotel-reservation:0.3.3
          name: hotel-reserv-frontend
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
      restartPolicy: Always
status: {}
