apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - command:
        - frontend
        image: deathstarbench/hotel-reservation:0.3.3
        name: hotel-reserv-frontend
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 1000m
      - name: frontend-envoy
        image: envoyproxy/envoy:v1.22.0
        command:
        - envoy
        - -c
        - /etc/envoy/envoy.yaml
        - --service-cluster
        - frontend
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: frontend-envoy-config
          mountPath: /etc/envoy
        - name: frontend-envoy-scripts
          mountPath: /etc/envoy/scripts
        ports:
        - containerPort: 15001
      volumes:
      - name: frontend-envoy-config
        configMap:
          name: frontend-envoy-config
          items:
          - key: envoy.yaml
            path: envoy.yaml
      - name: frontend-envoy-scripts
        configMap:
          name: frontend-envoy-config
          items:
          - key: token_check.lua
            path: token_check.lua
      restartPolicy: Always 