apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-envoy-config
  namespace: hr1
data:
  token_check.lua: |
    {{ .Files.Get "scripts/token_check.lua" }}
  envoy.yaml: |
    static_resources:
      listeners:
      - name: frontend_listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 15001
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: frontend_http
              codec_type: AUTO
              route_config:
                name: frontend_route
                virtual_hosts:
                - name: frontend_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: frontend_service
              http_filters:
              - name: envoy.filters.http.lua
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                  source_codes:
                    token_check:
                      filename: "/etc/envoy/scripts/token_check.lua"
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
      - name: frontend_service
        connect_timeout: 0.25s
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: frontend_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 5000 